#!/usr/bin/python

import sys
from glasses import GlassesCore

print sys.argv.count

if len(sys.argv) < 3:
    sys.exit('This commands require 3 arguments')

glasses = GlassesCore()
files =  glasses.getFilesRecursive(sys.argv[1])
glasses.searchOnFiles(files, sys.argv[2])
